{% set name = "langgraph-sdk" %}
{% set version = "0.1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph_sdk-{{ version }}.tar.gz
  sha256: addffc33554b690e81525c12fe9b2656cc7b740678e4724bc706d1ca13b3de93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0,<4.0
    - httpx >=0.25.2
    - httpx-sse >=0.4.0
    - orjson >=3.10.1

test:
  imports:
    - langgraph_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: SDK for interacting with LangGraph API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
