{% set name = "langgraph-sdk" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: b3bd04c6be4fa382996cd2be8fbc1e7cc94857d2bc6b6f4599a7f2a245975303
  - url: https://github.com/langchain-ai/langgraph/archive/refs/tags/sdk=={{ version }}.tar.gz
    sha256: 9f50895801c3a8c860f1f58e49f275b634c2982287d7e13f5de63c3101516f2a
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - httpx >=0.25.2
    - orjson >=3.10.1
    # import failed with -> ModuleNotFoundError: No module named 'typing_extensions'
    # https://github.com/langchain-ai/langgraph/blob/0.4.7/libs/sdk-py/langgraph_sdk/auth/types.py#L19
    - typing_extensions

test:
  source_files:
    - gh_src/libs/sdk-py/tests
    - gh_src/docs/docs/cloud/reference/api/openapi.json
  imports:
    - langgraph_sdk
    - langgraph_sdk.auth
    - langgraph_sdk.client
    - langgraph_sdk.schema
    - langgraph_sdk.sse
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v gh_src/libs/sdk-py/tests
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: SDK for interacting with LangGraph API
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: This repository contains the Python SDK for interacting with the LangGraph Platform REST API.
  dev_url: https://github.com/langchain-ai/langgraph/tree/main/libs/sdk-py
  doc_url: https://github.com/langchain-ai/langgraph/blob/main/libs/sdk-py/README.md

extra:
  recipe-maintainers:
    - jan-janssen
