{% set name = "langgraph-sdk" %}
{% set version = "0.1.70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: cc65ec33bcdf8c7008d43da2d2b0bc1dd09f98d21a7f636828d9379535069cf9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - httpx >=0.25.2
    - orjson >=3.10.1

test:
  imports:
    - langgraph_sdk
    - langgraph_sdk.auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: SDK for interacting with LangGraph API
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: This repository contains the Python SDK for interacting with the LangGraph Platform REST API.
  dev_url: https://github.com/langchain-ai/langgraph/tree/main/libs/sdk-py
  doc_url: https://github.com/langchain-ai/langgraph/blob/main/libs/sdk-py/README.md

extra:
  recipe-maintainers:
    - jan-janssen
